export const errors = {
    ACCESS_DENIED: 'Access denied',
    ACCOUNT_ALREADY_VERIFIED: 'Account already verified',
    ACCOUNT_HAS_BEEN_BLOCKED: 'Account has been blocked',
    ACCOUNT_HAS_BEEN_SUSPENDED: 'Account has been suspended',
    ACCOUNT_NOT_YET_VERIFIED: 'Account not yet verified',
    COMPANY_NOT_FOUND: 'Company not found',
    EMAIL_ALREADY_EXISTS: 'Email already exists',
    EMAIL_NOT_FOUND: 'Email not found',
    INACTIVE_ACCOUNT: 'Inactive account',
    INVALID_PASSWORD_RECOVERY_TOKEN: 'Invalid password recovery token',
    INVALID_REQUEST: 'Invalid request',
    INVALID_VERIFICATION_CODE: 'Invalid verification code',
    KANBAN_CARD_NOT_FOUND: 'Kanban card not found',
    KANBAN_COLUMN_NOT_FOUND: 'Kanban column not found',
    EVENT_NOT_FOUND:'Event not found',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    TASK_NOT_FOUND: 'Task not found',
    TOO_MANY_MESSAGES: 'Too many messages, please try again in a few minutes',
    TOO_MANY_REQUESTS: 'Too many requests, please try again in a few minutes',
    USER_NOT_FOUND: 'User not found',
    WRONG_AUTHENTICATION: 'Wrong authentication',
    WRONG_CREDENTIALS: 'Wrong credentials',
    WRONG_PASSWORD: 'Wrong password',
    ZIP_CODE_NOT_FOUND: 'Zip code not found'
};