import { config } from "dotenv";
config({ path: `.env.${process.env.NODE_ENV || "development"}` });

export const vars = {
  env: process.env.NODE_ENV || "",
  host: process.env.HOST || "",
  port: parseInt(process.env.PORT) || 0,
  socketPort: parseInt(process.env.SOCKET_PORT) || 0,
  maxApiRequestsPerHour: parseInt(process.env.MAX_API_REQUESTS_PER_HOUR) || 0,
  verificationCodeExpInHours:
    parseInt(process.env.VERIFICATION_CODE_EXP_IN_HOURS) || 0,
  recoveryTokenExpInHours:
    parseInt(process.env.RECOVERY_TOKEN_EXP_IN_HOURS) || 0,
  mongoUri: process.env.MONGO_URI || "",
  mongoDb: process.env.MONGO_DB || "",
  facebookClientId: process.env.FACEBOOK_CLIENT_ID || "",
  facebookClientSecret: process.env.FACEBOOK_CLIENT_SECRET || "",
  facebookClientAuthUrl: process.env.FACEBOOK_CLIENT_AUTH_URL || "",
  facebookClientRedirectUrl: process.env.FACEBOOK_CLIENT_REDIRECT_URL || "",
  facebookSuccessUrl: process.env.FACEBOOK_SUCCESS_URL || "",
  facebookErrorUrl: process.env.FACEBOOK_ERROR_URL || "",
  googleClientId: process.env.GOOGLE_CLIENT_ID || "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET || "",
  googleClientAuthUrl: process.env.GOOGLE_CLIENT_AUTH_URL || "",
  googleClientRedirectUrl: process.env.GOOGLE_CLIENT_REDIRECT_URL || "",
  googleSuccessUrl: process.env.GOOGLE_SUCCESS_URL || "",
  googleErrorUrl: process.env.GOOGLE_ERROR_URL || "",
  awsRegion: process.env.AWS_REGION || "",
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID || "",
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "",
  awsBucketName: process.env.AWS_BUCKET_NAME || "",
  fastlyCdnUrl: process.env.FASTLY_CDN_URL || "",
  appLink: process.env.APP_LINK || "",
  dashLink: process.env.DASH_LINK || "",
  smtpHost: process.env.SMTP_HOST || "",
  smtpPort: parseInt(process.env.SMTP_PORT) || 0,
  smtpUser: process.env.SMTP_USER || "",
  smtpPass: process.env.SMTP_PASS || "",
  jwtSecretKey: process.env.JWT_SECRET_KEY || "",
  jwtExpiresIn: process.env.JWT_EXPIRES_IN || "",
  jwtRefreshKey: process.env.JWT_SECRET_KEY || "",
  jwtRefreshExpiresIn: process.env.JWT_EXPIRES_IN || "",
  appleClientID: process.env.APPLE_CLIENT_ID || "",
  appleCallbackURL: process.env.APPLE_CALLBACK_URL,
  appleTeamId: process.env.APPLE_TEAM_ID || "",
  appleKeyIdentifier: process.env.APPLE_KEY_IDENTIFIER || "",
  applePrivateKeyPath: process.env.APPLE_PRIVE_KEY || "",
  appleClientAuthUrl: process.env.APPLE_CLIENT_AUTH_URL || "",
  appleClientRedirectUrl: process.env.APPLE_CLIENT_REDIRECT_URL || "",
  appleSuccessUrl: process.env.APPLE_SUCCESS_URL || "",
  appleErrorUrl: process.env.APPLE_ERROR_URL || "",
  googleAnalyticsPropertyId: process.env.GA_PROPERTY_ID || "",
  googleAnalyticsClientEmail: process.env.GA_CLIENT_EMAIL || "",
  googleAnalyticsPrivateKey: process.env.GA_PRIVATE_KEY || "",
};
